package odra.cli.parser;

/**
 * This class represents tokens returned by the CLILexer class.
 *
 * @author raist
 */

public class CLIToken {
	public byte kind;
	public String value;

	public CLIToken(byte kind, String value) {
		this.kind = kind;
		this.value = value;

		if(this.kind != STRING_LITERAL)
			for (byte i = ADD; i < kindstr.length; i++)
				if (value.equalsIgnoreCase(kindstr[i])) {
					this.kind = i;
					break;
				}
	}

	public static String spell(byte kind) {
		return kind >= ADD ? "'" + kindstr[kind] + "'" : kindstr[kind];
	}

	public final static byte
		ERROR = 0,
		EOF = 1,
		EOL = 2,
		NAME = 3,
		INTEGER_LITERAL = 4,
		STRING_LITERAL = 5,
		COLON = 6,
		AT = 7,
		SLASH = 8,
		DOT = 9,
		QUOTE = 10,
		ADD = 11,
		REMOVE = 12,
		MODULE = 13,
		QUIT = 14,
		DUMP = 15,
		CM = 16,
		LS = 17,
		PWM = 18,
		EDIT = 19,
		PROCEDURE = 20,
		CONNECT = 21,
		DISCONNECT = 22,
		HELP = 23,
		USER = 24,
		IDENTIFIED = 25,
		BY = 26,
		VARIABLE = 27,
		TYPE = 28,
		COMPILE = 29,
		DISASSEMBLE = 30,
		STORE = 31,
		MEMORY = 32,
		LOAD = 33,
		USING = 34,
		LPAREN = 35,
		RPAREN = 36,
		CREATE = 37,
		INDEX = 38,
		ON = 39,
		ASSEMBLED = 40,
		SET = 41,
		SHOW = 42,
		LINK = 43,
		EXPLAIN = 44,
		OPTIMIZATION = 45,
		BAR = 46,
		NAVIGATOR = 47,
		INQUIRER = 48,
		AS = 49,
		WRAPPER = 50,
		SDWRAPPER = 51,
		SWARDWRAPPER = 52,
		JULIETCODE = 53,
		BATCH = 54,
		CD = 55,
		PWD = 56,
		MEMMONITOR = 57,
		CLIENT = 58,
		SERVER = 59,
		ENDPOINT = 60,
		WITH = 61,
		BENCHMARK = 62,
		STATE = 63,
		PATH = 64,
		SERVICE_NAME = 65,
		PORT_NAME = 66,
		NS = 67,
		EQ = 68,
		COMMA = 69,
		STARTED = 70,
		STOPPED = 71,
		PROXY = 72,
		TYPECHECKER = 73,
		VIEW = 74,
		REFRESH = 75,
		METALINK = 76,
		AST_VISUALIZER = 77,
		SUSPEND = 78,
		RESUME = 79,
		WHATIS = 80,
		IF = 81,
		THEN = 82,
		NOT = 83,
		EXISTS = 84,
		ECHO = 85,
		TMPINDEX = 86,
		INTERFACE = 87,
		ASSIGN = 88,
		TO = 89,
		FROM = 90,
		GRIDLINK = 91,
		JOINTOGRID = 92,
		REMOVEFROMGRID = 93,
		CONNECTTOGRID = 94,
		PORTTYPE = 95,
		PROMOTE = 96,
		ROLE = 97,
		AC = 98,
		GRANT = 99,
		PRIVILEGE = 100,
		RESTRICTION = 101,
		ALLOW = 102,
		DENY = 103,
		READ = 104,
		UPDATE = 105,
		DELETE = 106,
		OBJECT = 107,
		MODE = 108,
		VALUE = 109,
		SCHEMA = 110,
		BODY = 111,
		ALTER = 112,
		QUIET = 113,
		DEFRAGMENT = 114;

	private static String[] kindstr = {
			"<error>",
			"<eof>",
			"<eol>",
			"<identifier>",
			"<integer-literal>",
			"<string-literal>",
			":",
			"@",
			"/",
			".",
			"\"",
			"add",
			"remove",
			"module",
			"quit",
			"dump",
			"cm",
			"ls",
			"pwm",
			"edit",
			"procedure",
			"connect",
			"disconnect",
			"help",
			"user",
			"identified",
			"by",
			"variable",
			"type",
			"compile",
			"disassemble",
			"store",
			"memory",
			"load",
			"using",
			"(",
			")",
			"create",
			"index",
			"on",
			"assembled",
			"set",
			"show",
			"link",
			"explain",
			"optimization",
			"|",
			"navigator",
			"inquirer",
			"as",
			"wrapper",
			"sdwrapper",
			"swardwrapper",
			"julietcode",
			"batch",
			"cd",
			"pwd",
			"memmonitor",
			"client",
			"server",
			"endpoint",
			"with",
			"benchmark",
			"state",
			"path",
			"service",
			"port",
			"ns",
			"eq",
			"comma",
			"started",
			"stopped",
			"proxy",
			"typechecker",
			"view",
			"refresh",
			"metalink",
			"astvisualizer",
			"suspend",
			"resume",
			"whatis",
			"if",
			"then",
			"not",
			"exists",
			"echo",
			"tmpindex",
			"interface",
			"assign",
			"to",
			"from",
			"gridlink",
			"jointogrid",
			"removefromgrid",
			"connecttogrid",
			"portType",
			"promote",
			"role",
			"ac",
			"grant",
			"privilege",
			"restriction",
			"allow",
			"deny",
			"read",
			"update",
			"delete",
			"object",
			"mode",
			"value",
			"schema",
			"body", 
			"alter",
			"quiet",
			"defragment"
	};
}
