
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Aug 10 18:46:21 EDT 2014
//----------------------------------------------------

package odra.sbql.parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int UNLINK = 53;
  public static final int DIVIDE = 18;
  public static final int BooleanLiteralExpCS = 68;
  public static final int WITH = 56;
  public static final int GREATEREQUALS = 22;
  public static final int TUPLE = 57;
  public static final int UMINUS = 14;
  public static final int CASE = 37;
  public static final int LOWER = 21;
  public static final int GREATER = 20;
  public static final int FOR = 39;
  public static final int MINUS = 16;
  public static final int DELETE = 52;
  public static final int SEMICOLON = 10;
  public static final int ASSIGN_DIVIDE = 31;
  public static final int TUPLETYPE = 58;
  public static final int NOP = 46;
  public static final int IN = 60;
  public static final int COMMA = 11;
  public static final int THROW = 44;
  public static final int LOWEREQUALS = 23;
  public static final int ASSIGN_ADD = 28;
  public static final int DOUBLEDOT = 26;
  public static final int LEFTSQUARE = 6;
  public static final int DIFFERENT = 19;
  public static final int CollectionTypeIdentifierCS = 69;
  public static final int PLUS = 15;
  public static final int ASSIGN = 27;
  public static final int IF = 32;
  public static final int DOT = 25;
  public static final int CONTEXT = 61;
  public static final int StringLiteralExpCS = 65;
  public static final int EOF = 0;
  public static final int RealLiteralExpCS = 66;
  public static final int LINK = 49;
  public static final int RETURN = 45;
  public static final int EQUAL = 13;
  public static final int error = 1;
  public static final int DateLiteralExpCS = 64;
  public static final int TRY = 42;
  public static final int RIGHTSQUARE = 7;
  public static final int FROM = 54;
  public static final int SWITCH = 36;
  public static final int ASSIGN_SUBTRACT = 29;
  public static final int RIGHTPAR = 3;
  public static final int VERT = 12;
  public static final int TIMES = 17;
  public static final int FOREACH = 55;
  public static final int RIGHTBRACE = 5;
  public static final int COLON = 8;
  public static final int ENDIF = 35;
  public static final int ELSE = 34;
  public static final int TO = 50;
  public static final int WHILE = 40;
  public static final int INSERT = 48;
  public static final int CREATE = 47;
  public static final int DEFAULT = 38;
  public static final int LEFTPAR = 2;
  public static final int LET = 59;
  public static final int LEFTBRACE = 4;
  public static final int THEN = 33;
  public static final int BODY = 62;
  public static final int IntegerLiteralExpCS = 63;
  public static final int simpleNameCS = 67;
  public static final int RIGHTARROW = 24;
  public static final int ASSIGN_MULTIPLY = 30;
  public static final int DO = 41;
  public static final int DOUBLECOLON = 9;
  public static final int REPLACE = 51;
  public static final int CATCH = 43;
}

